# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a11a60289b552ba0e6503c832e1174260e54409649892239768d9aed9509478729ac8058e3dd13ab930cb6b26bedbc07c8241c77e0272bc42a2bfba769be822

test:
  secret_key_base: da9e4a6c6a9993cccfa0ece02fffe39045cc02233261f5baa9ed7df91c49f1f166c5cf6084549af3ff625bd9f933d569979c5e05d4795e160065a889cde3064d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
